<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Chaipoints-MacBook-Air.local" name="in.shark.online.web.test.outlet.TestGetOrderByIdApiTestNg" tests="1" failures="0" timestamp="21 Nov 2019 06:56:40 GMT" time="6.428" errors="1">
  <testcase name="testGetOrdersById" time="6.428" classname="in.shark.online.web.test.outlet.TestGetOrderByIdApiTestNg">
    <error type="java.lang.AssertionError" message="Status expected:&lt;200 OK&gt; but was:&lt;404 NOT_FOUND&gt;

&gt; GET https://qa3-api.chaipoint.com/outlet-pos-api/api/order/id?orderId=CH4374700000002
&gt; WebTestClient-Request-Id: [1]
&gt; Cookie: [app_cp=e7ab992f-b94e-4017-95bd-a5dabb917698]
&gt; service.auth.key: [1234567]
&gt; content-type: [application/json;charset=UTF-8]

No content

&lt; 404 NOT_FOUND Not Found
&lt; Date: [Thu, 21 Nov 2019 06:56:33 GMT]
&lt; Content-Type: [application/json;charset=UTF-8]
&lt; Transfer-Encoding: [chunked]
&lt; Connection: [keep-alive]
&lt; Server: [Apache-Coyote/1.1]
&lt; X-Content-Type-Options: [nosniff]
&lt; X-XSS-Protection: [1; mode=block]
&lt; Cache-Control: [no-cache, no-store, max-age=0, must-revalidate]
&lt; Pragma: [no-cache]
&lt; Expires: [0]
&lt; X-Frame-Options: [DENY]
&lt; Access-Control-Allow-Headers: [Content-Type, Cookie, service.auth.key]
&lt; Access-Control-Allow-Credentials: [true]
&lt; Access-Control-Max-Age: [86400]

{&quot;timestamp&quot;:1574319393639,&quot;status&quot;:404,&quot;error&quot;:&quot;Not Found&quot;,&quot;message&quot;:&quot;No handler found for GET /outlet-pos-api/api/order/id&quot;,&quot;path&quot;:&quot;/outlet-pos-api/api/order/id&quot;}
">
      <![CDATA[java.lang.AssertionError: Status expected:<200 OK> but was:<404 NOT_FOUND>

> GET https://qa3-api.chaipoint.com/outlet-pos-api/api/order/id?orderId=CH4374700000002
> WebTestClient-Request-Id: [1]
> Cookie: [app_cp=e7ab992f-b94e-4017-95bd-a5dabb917698]
> service.auth.key: [1234567]
> content-type: [application/json;charset=UTF-8]

No content

< 404 NOT_FOUND Not Found
< Date: [Thu, 21 Nov 2019 06:56:33 GMT]
< Content-Type: [application/json;charset=UTF-8]
< Transfer-Encoding: [chunked]
< Connection: [keep-alive]
< Server: [Apache-Coyote/1.1]
< X-Content-Type-Options: [nosniff]
< X-XSS-Protection: [1; mode=block]
< Cache-Control: [no-cache, no-store, max-age=0, must-revalidate]
< Pragma: [no-cache]
< Expires: [0]
< X-Frame-Options: [DENY]
< Access-Control-Allow-Headers: [Content-Type, Cookie, service.auth.key]
< Access-Control-Allow-Credentials: [true]
< Access-Control-Max-Age: [86400]

{"timestamp":1574319393639,"status":404,"error":"Not Found","message":"No handler found for GET /outlet-pos-api/api/order/id","path":"/outlet-pos-api/api/order/id"}

	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:200)
	at org.springframework.test.web.reactive.server.StatusAssertions.assertStatusAndReturn(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.StatusAssertions.isOk(StatusAssertions.java:67)
	at in.shark.online.web.test.outlet.TestGetOrderByIdApiTestNg.testGetOrdersById(TestGetOrderByIdApiTestNg.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:182)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:194)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: Status expected:<200 OK> but was:<404 NOT_FOUND>
	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:55)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:82)
	at org.springframework.test.web.reactive.server.StatusAssertions.lambda$assertStatusAndReturn$4(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:197)
	... 34 more
]]>
    </error>
  </testcase> <!-- testGetOrdersById -->
</testsuite> <!-- in.shark.online.web.test.outlet.TestGetOrderByIdApiTestNg -->
